
-- Cria tabela telefone
create table tb_telefones (
	id BIGINT generated by default as identity,
	ddd VARCHAR(2) NOT NULL,
	numero VARCHAR(20) NOT NULL,
	primary key(id)
);

create table tb_enderecos(
    id BIGINT generated by default as identity,
    endereco VARCHAR(100) NOT NULL,
    primary key(id)
);

create table tb_horarios(
    id BIGINT generated by default as identity,
    horario VARCHAR(50) NOT NULL,
    primary key(id)
);

-- Insere dados
INSERT INTO tb_telefones (ddd, numero) values ('51','51 9090-9080');

INSERT INTO tb_telefones (ddd, numero) values
('51','9170-7070'),
('54','9280-8080'),
('55','9390-9090');

INSERT INTO tb_enderecos (endereco) values
('Rua Assis Brasil, 87 - Porto Alegre'),
('Rua Cristovão Colombo, 123 - Porto Alegre'),
('Rua Mario Totta, 12 - Porto Alegre');

INSERT INTO tb_horarios (horario) values
('Segunda-Sexta das 10 às 18 horas'),
('Sábados das 09 às 12 horas');
