
-- Cria tabela telefone
create table tb_telefones (
	id BIGINT generated by default as identity,
	numero VARCHAR(20) NOT NULL,
	primary key(id)
);

create table tb_enderecos(
    id BIGINT generated by default as identity,
    endereco VARCHAR(100) NOT NULL,
    primary key(id)
);

create table tb_horarios(
    id BIGINT generated by default as identity,
    horario VARCHAR(50) NOT NULL,
    primary key(id)
);

-- Insere dados
INSERT INTO tb_telefones (numero) values ('51 9090-9080');

INSERT INTO tb_telefones (numero) values
('51 9090-9080'),
('51 9090-9081'),
('51 9090-9091');

INSERT INTO tb_enderecos (endereco) values
('Rua Assis Brasil, 87 - Porto Alegre'),
('Rua Cristovão Colombo, 123 - Porto Alegre'),
('Rua Mario Totta, 12 - Porto Alegre');

INSERT INTO tb_horarios (horario) values
('Segunda-Sexta das 10 às 18 horas'),
('Sábados das 09 às 12 horas');
